//exportar los componentes:
export { addPostButton } from './addPostButton/addPostButton';
export { breedCard, AttributeBreed } from './breed/breed';
export { createAccountButton } from './createAccountButton/createAccountButton';
export { introBanner } from './introBanner/introbanner';
export { LoginButton } from './LoginButton/LoginButton';
export { PasswordField } from './PasswordField/PasswordField';
export { postCard, AttributePostCard } from './postCard/postCard';
export { postPicture, AttributePicture } from './postPicture/postPicture';
export { profileBanner, AttributeProfile } from './profileBanner/profileBanner';
export { saveButton } from './saveButton/saveButton';
export { SelectFromDevice } from './selectFromDevice/selectFromDevice';
export { singleBanner, AttributeBanner } from './singleBanner/singleBanner';
export { userDescription, AttributeUser } from './userDescription/userDescription';
export { UsernameField } from './UsernameField/UsernameField';
export { welcomeMessage, AttributeMessage } from './welcomeMessage/welcomeMessage';
export { InputField } from './InputField/InputField';
export { CheckboxField } from './CheckboxField/CheckboxField';
export { SignupButton } from './SignupButton/SignupButton';
export { LogoutButton } from './logoutButton/logoutButton';
export {PetgramBanner} from './petgramBanner/petgramBanner';